# Generated by Django 5.1.5 on 2025-03-28 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Landmark',
        ),
    ]
