# Generated by Django 5.1.5 on 2025-03-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='type',
            field=models.CharField(choices=[('C', 'cultural'), ('H', 'historical'), ('N', 'natural')], default='O', max_length=1),
        ),
    ]
