# Generated by Django 5.1.5 on 2025-03-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_landmark_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='type',
            field=models.CharField(choices=[('C', 'Cultural'), ('H', 'Historical'), ('N', 'Natural')], default='O', max_length=1),
        ),
    ]
