# Generated by Django 5.1.5 on 2025-03-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_alter_landmark_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='states',
            name='region',
            field=models.CharField(choices=[('new england', 'New England'), ('mid-atlantic', 'Mid-Atlantic'), ('midwest', 'Midwest'), ('south atlantic', 'South Atlantic'), ('south central', 'South Central'), ('mountain', 'Mountain'), ('pacific', 'Pacific')], default='midwest', max_length=15),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.city')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.activity')),
                ('gear', models.ManyToManyField(to='helloworld.gear')),
            ],
        ),
        migrations.CreateModel(
            name='Landmark_Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.ManyToManyField(to='helloworld.gear')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cusine', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.city')),
            ],
        ),
    ]
