# Generated by Django 5.1.5 on 2025-05-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0011_remove_landmark_gear_gear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='decription',
            new_name='description',
        ),
    ]
