# Generated by Django 5.1.5 on 2025-03-28 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('name', models.CharField(default='None', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('name', models.CharField(default='None', max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('opening_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('closing_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.states'),
        ),
    ]
