# Generated by Django 5.1.5 on 2025-03-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_delete_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
