# Generated by Django 5.1.5 on 2025-03-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_alter_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('name', models.CharField(default='None', max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('opening_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('closing_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.city')),
            ],
        ),
    ]
