# Generated by Django 5.1.5 on 2025-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0007_gear_states_region_activity_activity_gear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='decription',
            field=models.CharField(default='', max_length=200),
        ),
    ]
