# Generated by Django 5.1.5 on 2025-03-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0008_activity_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('O', 'outdoor'), ('I', 'indoor')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='resturant',
            name='price',
            field=models.CharField(choices=[('$', 'cheap'), ('$$', 'reasonable'), ('$$$', 'expensive'), ('$$$$', 'very expensive')], default='-', max_length=5),
        ),
    ]
