# Generated by Django 5.1.5 on 2025-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0009_activity_type_resturant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='closing_time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='resturant',
            name='opening_time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
