# Generated by Django 5.1.5 on 2025-03-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0010_alter_resturant_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark_gear',
            name='gear',
        ),
        migrations.RemoveField(
            model_name='landmark_gear',
            name='landmark',
        ),
        migrations.DeleteModel(
            name='Activity_Gear',
        ),
        migrations.DeleteModel(
            name='Gear',
        ),
        migrations.DeleteModel(
            name='Landmark_Gear',
        ),
    ]
